#!/bin/bash

# Fijamos el arranqe de una red de 3 nodos (administrador, registrador y presidente)
node_name=('secretary_node' 'registrar_node' 'president_node' 'commoner_node')
num_nodes="${#node_name[@]}"
